# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'iSalah' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iSalah
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'NVActivityIndicatorView'
  pod 'BEMCheckBox'
end

target 'iSalahWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iSalah
  pod 'Alamofire'
end
